---
# First the tasks that need a priviledged user
- name: Installation of prerequisistes (Bootstrapping)
  hosts: all
  become: yes
  remote_user: ububtu
    
  tasks:

    - name: Update the APT Repository Cache (once a day)
      apt:
        update_cache: yes
        cache_valid_time: 86400
        
    - name: Add Java 8 using apt
      apt:
        name: openjdk-8-jdk-headless
        state: present
        
    - name: Setup JAVA_HOME Environment Variable
      lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
      
    - name: Add Maven 3 using apt
      apt:
        name: maven
        state: present       
 
    - name: Add Git Latest using apt
      apt:
        name: git
        state: present
        
    - name: Add Unzip Git Latest using apt
      apt:
        name: unzip
        state: present
 
- name: Installation of SMP Software
  hosts: all
  remote_user: ubuntu

  vars_files:
  # File containing the information of the AP keystore
    - provision/keystore/keystore_vars.yml  
  vars:
   
    tomcat_user: "{{ansible_user_id}}"
    tomcat_group: "{{ansible_user_id}}"
    tomcat_port: 8080

    home_dir: "/home/{{ansible_user_id}}"    
    sources_dir: "{{ home_dir }}/sources"
    tomcat_dir: "{{home_dir}}/apache-tomcat-8.0.38"
    smp_data: "{{tomcat_dir}}/smp-data"
    smp_keystore_path: "{{tomcat_dir}}/conf/smpKeystore.jks"

    smp_id: TEST-SMP
    
  tasks:
      
  - name: Create Downloads Directory
    file: path="{{home_dir}}/Downloads" state=directory

  - name: Download Tomcat 8.0.38
    get_url: 
      url: "http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.0.38/bin/apache-tomcat-8.0.38.tar.gz"
      dest: "{{home_dir}}/Downloads/apache-tomcat-8.0.38.tar.gz"
      checksum: md5:cb1f5e098024df2bb19c581eca180a2a
  
  - name: Deploy Tomcat 8.0.38
    unarchive:
    args:
      src: "{{home_dir}}/Downloads/apache-tomcat-8.0.38.tar.gz"
      dest: "{{home_dir}}"
      remote_src: yes
      creates: "{{home_dir}}/apache-tomcat-8.0.38"
    register: tomcat_deploy_result

  - name: Remove default ROOT webapp
    file: path="{{tomcat_dir}}/webapps/{{item}}" state=absent
    with_items:
      - ROOT
      - ROOT.war
    when: tomcat_deploy_result | changed 
    
  - name: Configure Tomcat Port
    template: src=server.xml.j2 dest="{{tomcat_dir}}/conf/server.xml" mode=600 backup=yes
  
  - name: Configure Catalina classpath (required for config files)
    lineinfile: dest="{{tomcat_dir}}/conf/catalina.properties" regexp="^shared.loader=" line="shared.loader=${catalina.base}/conf"  

  - name: Configure smp.webapp.properties.path (required for config files)
    lineinfile: dest="{{tomcat_dir}}/conf/catalina.properties" regexp="^smp.webapp.properties.path=" line="smp.webapp.properties.path={{tomcat_dir}}/conf/webapp.properties"

  - name: Configure smp-server.properties.path (required for config files)
    lineinfile: dest="{{tomcat_dir}}/conf/catalina.properties" regexp="^smp.server.properties.path=" line="smp.server.properties.path={{tomcat_dir}}/conf/smpserver.properties"    

  - name: Configure smp-server.properties.path (required for config files)
    lineinfile: dest="{{tomcat_dir}}/conf/catalina.properties" regexp="^peppol.pd.client.properties.path=" line="peppol.pd.client.properties.path={{tomcat_dir}}/conf/pdclient.properties"    

  - name: Clone the PHAX SMP Server in {{ sources_dir }}/peppol-smp-server
#   git: repo=https://github.com/phax/peppol-smp-server.git dest={{ sources_dir }}/peppol-smp-server version=peppol-smp-server-parent-pom-4.1.2
    git: repo=https://github.com/phax/peppol-smp-server.git dest={{ sources_dir }}/peppol-smp-server version=master
    register: smp_result

  - name: Build SMP Server from {{ sources_dir }}/peppol-smp-server 
    when: smp_result | changed
    command: "mvn -DskipTests clean install"
    args:
      chdir: "{{ sources_dir }}/peppol-smp-server"

  - name: Deploy SMP Server to tomcat
#    copy: src="{{ sources_dir }}/peppol-smp-server/peppol-smp-server-webapp/target/peppol-smp-server-webapp-4.1.2.war" dest="{{tomcat_dir}}/webapps/ROOT.war"
    copy: src="{{ sources_dir }}/peppol-smp-server/peppol-smp-server-webapp/target/peppol-smp-server-webapp-5.0.0-SNAPSHOT.war" dest="{{tomcat_dir}}/webapps/ROOT.war"

  - name: Copy SMP Keystore to tomcat
    copy: src="{{smp_keystore}}" dest="{{smp_keystore_path}}"  mode=0600 backup=yes

  - name: Configure SMP Server (smp-server.properties)
    template: src=smp-server.properties.j2 dest="{{tomcat_dir}}/conf/smpserver.properties" mode=600 backup=yes

  - name: Configure SMP Server (webapp.properties)
    template: src=webapp.properties.j2 dest="{{tomcat_dir}}/conf/webapp.properties" mode=600 backup=yes

  - name: Configure SMP Server (pd-client.properties)
    template: src=pd-client.properties.j2 dest="{{tomcat_dir}}/conf/pdclient.properties" mode=600 backup=yes
    
  - name: Create systemd service for tomcat
    template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service mode=600 backup=yes
    become: yes
    notify:
      - reload systemd
    
  - name: restart tomcat
    service: name=tomcat enabled=yes state=restarted
    become: yes
    
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
      become: yes
          